@startuml
autonumber
actor User
participant MA
participant BackEnd
database DB

activate User
User -> MA: Выбор виджета

activate MA
MA -> MA: Проверка логики местоположения виджета
MA -> BackEnd: http запрос на добавление виджета пользователю
activate BackEnd


BackEnd -> DB: SQL запрос на добавление виджета пользователю
activate DB
DB --> BackEnd: напиши sql-ответ
deactivate DB

BackEnd --> MA: Ответ(код) сервера на запрос
deactivate BackEnd

MA -> User: Успешное добавление виджета и сохранение настроек
deactivate MA
@enduml
