@startuml

skin rose
autonumber

actor Клиент as C
participant "Фронтенд" as FE
participant "Бэкенд" as BE
database "База данных" as DB

activate C

C -> FE: Выбрать слот для записи
activate FE
FE -> BE: HTTP-запрос: Забронировать слот
activate BE

BE -> DB: SQL-запрос проверка доступных слотов
activate DB
DB --> BE: Ок
BE -> DB: Записывает запись в BookedClients

DB --> BE: Запись успешно добавлена
deactivate DB
BE --> FE: Ответ с подтверждением записи
deactivate BE

FE --> C: Сообщение об успешной записи
deactivate FE
deactivate C

@enduml
