@startuml

skin rose


actor Клиент as C
participant "Фронтенд" as FE
participant "Бэкенд" as BE
database "База данных" as DB

C -> FE: 1. Запросить свободные слоты
activate FE
FE -> BE: 2. HTTP-запрос: Получить доступные слоты
activate BE
BE -> BE: 3. Валидация
BE -> DB: 4. SQL-запрос к AvailableSlots
activate DB
DB --> BE: 5. Возвращает список доступных слотов
deactivate DB

BE --> FE: 6. Возвращает JSON с доступными слотами
deactivate BE

FE --> C: 7. Отображает список доступных слотов
deactivate FE

C -> FE: 8. Выбрать слот для записи
activate FE
FE -> BE: 9. HTTP-запрос: Забронировать слот
activate BE

BE -> DB: 10. Валидация слота (проверка AvailableSlots)
activate DB
DB --> BE: 11. Подтверждает слот
BE -> DB: 12. Записывает запись в BookedClients

DB --> BE: 13. Запись успешно добавлена
deactivate DB
BE --> FE: 14. Подтверждение записи
deactivate BE

FE --> C: 15. Сообщение об успешной записи
deactivate FE
@enduml