openapi: 3.0.3
info:
  title: REST API Documentation
  description: >-
    Документирование REST-вызовов для работы с пользователями и избранными
    товарами
  version: 1.0.0
servers:
  - url: https://example.api/swagger/v1
tags:
  - name: users
    description: Методы для работы с пользователями
  - name: favorites
    description: Методы для работы с избранными товарами
paths:
  /users:
    get:
      tags:
        - users
      summary: Получить информацию о пользователе
      description: Возвращает информацию о пользователе, включая список избранных товаров.
      parameters:
        - name: user_id
          in: query
          description: Уникальный идентификатор пользователя
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
  /favorites:
    post:
      tags:
        - favorites
      summary: Добавить товар в избранное
      description: Добавляет товар в список избранных для пользователя.
      requestBody:
        description: Параметры для добавления товара в избранное
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FavoritesRequest'
      responses:
        '201':
          description: Товар успешно добавлен в избранное
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FavoritesResponse'
components:
  schemas:
    UserResponse:
      type: object
      properties:
        user_id:
          type: integer
          example: 123
        login:
          type: string
          example: john_kisa
        favorite_items:
          type: array
          items:
            $ref: '#/components/schemas/FavoriteItem'
    FavoriteItem:
      type: object
      properties:
        item_id:
          type: integer
          example: 1
        item_name:
          type: string
          example: Товар 1
        date_add:
          type: string
          format: date-time
          example: '2024-12-25'
    FavoritesRequest:
      type: object
      properties:
        user_id:
          type: integer
          example: 123
        item_id:
          type: integer
          example: 456
    FavoritesResponse:
      type: object
      properties:
        favorite_item_id:
          type: integer
          example: 789
        item_id:
          type: integer
          example: 456
        date_add:
          type: string
          format: date-time
          example: '2024-12-25'
