@startuml

skin rose
autonumber

actor User
participant "Mobile App Widberries" as Frontend
participant "Backend" as Backend
database "PG" as Database

activate User
User -> Frontend: Нажимает кнопку "Доставка по дате"

activate Frontend
Frontend -> Backend: Запрос на получение данных о товарах, сгруппированных по датам доставки

activate Backend
Backend -> Database: Запрос на получение данных о товарах, сгруппированных по датам доставки

activate Database
Database -> Backend: Данные о товарах, сгруппированных по датам доставки
deactivate Database

Backend -> Frontend: Сгруппированные по датам доставки данные о товарах
deactivate Backend

Frontend -> User: Отображение товаров, сгруппированных по дате доставки
deactivate Frontend
deactivate User

@enduml
