openapi: 3.0.3
info:
  title: Swagger Petstore - OpenAPI 3.0
  description: |-
    This is a sample Pet Store Server based on the OpenAPI 3.0 specification.  You can find out more about
    Swagger at [https://swagger.io](https://swagger.io). In the third iteration of the pet store, we've switched to the design first approach!
    You can now help us improve the API whether it's by making changes to the definition itself or to the code.
    That way, with time, we can improve the API in general, and expose some of the new features in OAS3.

    _If you're looking for the Swagger 2.0/OAS 2.0 version of Petstore, then click [here](https://editor.swagger.io/?url=https://petstore.swagger.io/v2/swagger.yaml). Alternatively, you can load via the `Edit > Load Petstore OAS 2.0` menu option!_
    
    Some useful links:
    - [The Pet Store repository](https://github.com/swagger-api/swagger-petstore)
    - [The source API definition for the Pet Store](https://github.com/swagger-api/swagger-petstore/blob/master/src/main/resources/openapi.yaml)
  version: 1.0.11
servers:
  - url: https://carshare.swagger.io/api/v3


paths:
  /Users/{user_ID}/cars:
    get:
      summary: поиск машин 
      description: 'Поиск машин для поездки "Межгород" для конкретного пользователя'

      parameters:
        - name: user_ID
          in: path
          description: 'Уникальный идентификатор пользователя'
          required: true
          schema:
            type: integer
            
        - name: trip_type
          in: query
          description: 'Тариф поездки Межгород: Intercity '
          required: true
          schema:
            type: string
            
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cars'          


components:
  schemas:

    Cars:
      type: array
      items:
        type: object
        properties:
          car_ID:
            type: integer
            format: int64
            example: 101
            description: Идентификатор автомобиля
          car_details:
            type: string
            example: Hyundai Solaris, 2019, 1.6 л, 123 л.с., седан
            description: Описание автомобиля
          car_category:
            type: string
            example: Эконом
            description: Категория автомобиля
          last_adress:
            type: string
            example: Казань, ул. Советская, 24
            description: Адрес автомобиля после последней совершенной поездки
        
    
   