openapi: 3.0.3
info:
  title: Swagger  - OpenAPI 3.0
  description: примеры методов
  version: 1.0.0
servers:
  - url: https://petstore3.swagger.io/api/v3
  
tags:
  - name: photographer
    description: группа методов для работы с фотографами

    
paths:
  /photographers:
    get:
      tags:
        - photographer
      summary: фильтрация фотографов
      description: получить список фотографов по выбранной пользователем локации
      parameters:
        - name: radius
          in: query
          description: радиус области поиска фотографов
          required: false
          schema:
            type: number
        - name: latitude 
          in: query
          description: широта центра окружности для поиска фотографов
          required: false
          schema:
            type: number
        - name: longitude  
          in: query
          description: долгота центра окружности для поиска фотографов
          required: false
          schema:
            type: number
      responses:
       '200':
         description: Success
         content:
          application/json:
            schema:
              $ref: '#/components/schemas/Photographers'

              
components:
  schemas:
      
    Photographers:
      type: object
      properties:
        total_count:
          type: integer
          example: 404
          description: общее количество найденных профилей фотографов
        photographers:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
                example: Женя
                description: имя фотографа
              patronymic:
                type: string
                example: NULL
                description: отчество фотографа
              surname:
                type: string
                example: Фамилия
                description: фамилия фотографа
              rating:
                type: integer
                example: 8
                description: средний рейтинг фотографа
              avatar:
                type: string
                example: https://www.flickr.com/photos/186710613@N06/albums
                description: url, расположение аватарки фотографа
              location:
                type: string
                example: Москва, ул. Тверская
                description: локация фотографа (город+улица) наиболее близкие к входным параметрам
              latitude:
                type: number
                description: широта наиболее близкой локации фотографа к центру поиска (для отображения на карте)
              longitude:
                type: number
                description: долгота наиболее близкой локации фотографа к центру поиска (для отображения на карте)

      
      