
@startuml
actor User
participant frontend 
participant backend
database DB
autonumber

User -> frontend  : Нажимает на кнопку "Оформить"
frontend  -> backend :  Передача данных
activate backend
backend -> DB : SQL- запрос, \nсохранение данных
activate DB
DB --> backend : Успешное сохранение
deactivate DB
backend --> frontend  :  Возвращает json-ответ
frontend --> User : Отображение подтверждения бронирвания
deactivate backend
deactivate frontend 
@enduml
@enduml
