openapi: 3.0.3
info:
  title: API для управления психологами и клиентами
  description: API для работы с психологами, клиентами и их записями.
  version: 1.0.0
servers:
  - url: https://psi.swagger.io/api/v1
    description: Основной сервер API

tags:
  - name: Slots
    description: Управление слотами записи

paths:
  /slots/getAvailable:
    get:
      tags:
        - Slots
      summary: Получение доступных слотов для записи к психологу
      description: Возвращает список доступных слотов для записи к указанному психологу.
      parameters:
        - name: psychologist_id
          in: query
          required: true
          description: Уникальный идентификатор психолога
          schema:
            type: integer
      responses:
        '200':
          description: Успешный ответ с данными доступных слотов
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      description: Уникальный идентификатор слота
                      example: 1
                    psychologist_id:
                      type: integer
                      description: Уникальный идентификатор психолога
                      example: 101
                    slot_time:
                      type: string
                      format: date-time
                      description: Время слота
                      example: "2024-12-11T10:00:00Z"
                    is_available:
                      type: boolean
                      description: Доступность слота
                      example: true

  /slots/book:
    post:
      tags:
        - Slots
      summary: Бронирование слота для записи к психологу
      description: Позволяет забронировать слот для указанного клиента.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                slot_id:
                  type: integer
                  description: Уникальный идентификатор слота
                client_id:
                  type: integer
                  description: Уникальный идентификатор клиента
                user_name:
                  type: string
                  description: Имя и фамилия клиента
                email:
                  type: string
                  format: email
                  description: Электронная почта клиента
                phone:
                  type: string
                  description: Номер телефона клиента
                child_age:
                  type: integer
                  description: Возраст ребёнка клиента
              required:
                - slot_id
                - client_id
                - user_name
                - email
                - phone
      responses:
        '201':
          description: Слот успешно забронирован
          content:
            application/json:
              schema:
                type: object
                properties:
                  booking_id:
                    type: integer
                    description: Уникальный идентификатор бронирования
                    example: 5001
                  slot_id:
                    type: integer
                    description: Уникальный идентификатор слота
                    example: 101
                  client_id:
                    type: integer
                    description: Уникальный идентификатор клиента
                    example: 1001
